--[[
    Vehicle Audio Database
    
    This file contains vehicle audio names for the ForceVehicleEngineAudio native.
    The audio name is typically the vehicle model name in uppercase.
    
    Categories:
    - Super: High-end supercars
    - Sports: Sports cars
    - Muscle: American muscle cars
    - Sedans: 4-door sedans
    - Coupes: 2-door coupes
    - SUVs: Sport utility vehicles
    - Vans: Vans and minivans
    - Trucks: Pickup trucks and commercial trucks
    - Motorcycles: Bikes
    - Boats: Watercraft
    - Helicopters: Rotorcraft
    - Planes: Fixed-wing aircraft
    - Emergency: Police, fire, EMS vehicles
    - Military: Military vehicles
    - Industrial: Work vehicles
]]

VehicleAudio = {}

VehicleAudio.Categories = {
    {
        name = "Super",
        icon = "car",
        vehicles = {
            { audio = "ADDER", label = "Adder", model = "adder" },
            { audio = "AUTARCH", label = "Autarch", model = "autarch" },
            { audio = "BANSHEE2", label = "Banshee 900R", model = "banshee2" },
            { audio = "BULLET", label = "Bullet", model = "bullet" },
            { audio = "CHEETAH", label = "Cheetah", model = "cheetah" },
            { audio = "CYCLONE", label = "Cyclone", model = "cyclone" },
            { audio = "DEVESTE", label = "Deveste Eight", model = "deveste" },
            { audio = "EMERUS", label = "Emerus", model = "emerus" },
            { audio = "ENTITYXF", label = "Entity XF", model = "entityxf" },
            { audio = "ENTITY2", label = "Entity XXR", model = "entity2" },
            { audio = "FMJ", label = "FMJ", model = "fmj" },
            { audio = "FURIA", label = "Furia", model = "furia" },
            { audio = "GP1", label = "GP1", model = "gp1" },
            { audio = "INFERNUS", label = "Infernus", model = "infernus" },
            { audio = "ITALIGTB", label = "Itali GTB", model = "italigtb" },
            { audio = "ITALIGTB2", label = "Itali GTB Custom", model = "italigtb2" },
            { audio = "KRIEGER", label = "Krieger", model = "krieger" },
            { audio = "LE7B", label = "RE-7B", model = "le7b" },
            { audio = "NERO", label = "Nero", model = "nero" },
            { audio = "NERO2", label = "Nero Custom", model = "nero2" },
            { audio = "OSIRIS", label = "Osiris", model = "osiris" },
            { audio = "PENETRATOR", label = "Penetrator", model = "penetrator" },
            { audio = "PFISTER811", label = "811", model = "pfister811" },
            { audio = "PROTOTIPO", label = "X80 Proto", model = "prototipo" },
            { audio = "REAPER", label = "Reaper", model = "reaper" },
            { audio = "S80", label = "S80RR", model = "s80" },
            { audio = "SC1", label = "SC1", model = "sc1" },
            { audio = "SCRAMJET", label = "Scramjet", model = "scramjet" },
            { audio = "SHEAVA", label = "ETR1", model = "sheava" },
            { audio = "SULTANRS", label = "Sultan RS", model = "sultanrs" },
            { audio = "T20", label = "T20", model = "t20" },
            { audio = "TAIPAN", label = "Taipan", model = "taipan" },
            { audio = "TEMPESTA", label = "Tempesta", model = "tempesta" },
            { audio = "TEZERACT", label = "Tezeract", model = "tezeract" },
            { audio = "THRAX", label = "Thrax", model = "thrax" },
            { audio = "TIGON", label = "Tigon", model = "tigon" },
            { audio = "TORERO", label = "Torero", model = "torero" },
            { audio = "TURISMOR", label = "Turismo R", model = "turismor" },
            { audio = "TYRANT", label = "Tyrant", model = "tyrant" },
            { audio = "TYRUS", label = "Tyrus", model = "tyrus" },
            { audio = "VACCA", label = "Vacca", model = "vacca" },
            { audio = "VAGNER", label = "Vagner", model = "vagner" },
            { audio = "VISIONE", label = "Visione", model = "visione" },
            { audio = "VOLTIC", label = "Voltic", model = "voltic" },
            { audio = "XA21", label = "XA-21", model = "xa21" },
            { audio = "ZENTORNO", label = "Zentorno", model = "zentorno" },
            { audio = "ZORRUSSO", label = "Zorrusso", model = "zorrusso" },
        }
    },
    {
        name = "Sports",
        icon = "car",
        vehicles = {
            { audio = "ALPHA", label = "Alpha", model = "alpha" },
            { audio = "BANSHEE", label = "Banshee", model = "banshee" },
            { audio = "BESTIAGTS", label = "Bestia GTS", model = "bestiagts" },
            { audio = "BUFFALO", label = "Buffalo", model = "buffalo" },
            { audio = "BUFFALO2", label = "Buffalo S", model = "buffalo2" },
            { audio = "CARBONIZZARE", label = "Carbonizzare", model = "carbonizzare" },
            { audio = "COMET2", label = "Comet", model = "comet2" },
            { audio = "COMET3", label = "Comet Retro", model = "comet3" },
            { audio = "COMET4", label = "Comet Safari", model = "comet4" },
            { audio = "COMET5", label = "Comet SR", model = "comet5" },
            { audio = "COQUETTE", label = "Coquette", model = "coquette" },
            { audio = "DRAFTER", label = "8F Drafter", model = "drafter" },
            { audio = "ELEGY", label = "Elegy Retro", model = "elegy" },
            { audio = "ELEGY2", label = "Elegy RH8", model = "elegy2" },
            { audio = "FELTZER2", label = "Feltzer", model = "feltzer2" },
            { audio = "FLASHGT", label = "Flash GT", model = "flashgt" },
            { audio = "FUROREGT", label = "Furore GT", model = "furoregt" },
            { audio = "FUSILADE", label = "Fusilade", model = "fusilade" },
            { audio = "FUTO", label = "Futo", model = "futo" },
            { audio = "HOTRING", label = "Hotring Sabre", model = "hotring" },
            { audio = "INFERNUS2", label = "Infernus Classic", model = "infernus2" },
            { audio = "ISSI7", label = "Issi Sport", model = "issi7" },
            { audio = "ITALIGTO", label = "Itali GTO", model = "italigto" },
            { audio = "JESTER", label = "Jester", model = "jester" },
            { audio = "JESTER2", label = "Jester (Racecar)", model = "jester2" },
            { audio = "JESTER3", label = "Jester Classic", model = "jester3" },
            { audio = "JUGULAR", label = "Jugular", model = "jugular" },
            { audio = "KHAMELION", label = "Khamelion", model = "khamelion" },
            { audio = "KURUMA", label = "Kuruma", model = "kuruma" },
            { audio = "KURUMA2", label = "Kuruma (Armored)", model = "kuruma2" },
            { audio = "LOCUST", label = "Locust", model = "locust" },
            { audio = "LYNX", label = "Lynx", model = "lynx" },
            { audio = "MASSACRO", label = "Massacro", model = "massacro" },
            { audio = "MASSACRO2", label = "Massacro (Racecar)", model = "massacro2" },
            { audio = "NEO", label = "Neo", model = "neo" },
            { audio = "NEON", label = "Neon", model = "neon" },
            { audio = "NINEF", label = "9F", model = "ninef" },
            { audio = "NINEF2", label = "9F Cabrio", model = "ninef2" },
            { audio = "OMNIS", label = "Omnis", model = "omnis" },
            { audio = "PARAGON", label = "Paragon R", model = "paragon" },
            { audio = "PARIAH", label = "Pariah", model = "pariah" },
            { audio = "PENUMBRA", label = "Penumbra", model = "penumbra" },
            { audio = "PENUMBRA2", label = "Penumbra FF", model = "penumbra2" },
            { audio = "RAIDEN", label = "Raiden", model = "raiden" },
            { audio = "RAPIDGT", label = "Rapid GT", model = "rapidgt" },
            { audio = "RAPIDGT2", label = "Rapid GT Cabrio", model = "rapidgt2" },
            { audio = "RAPTOR", label = "Raptor", model = "raptor" },
            { audio = "REVOLTER", label = "Revolter", model = "revolter" },
            { audio = "RUSTON", label = "Ruston", model = "ruston" },
            { audio = "SCHAFTER3", label = "Schafter V12", model = "schafter3" },
            { audio = "SCHAFTER4", label = "Schafter LWB", model = "schafter4" },
            { audio = "SCHLAGEN", label = "Schlagen GT", model = "schlagen" },
            { audio = "SCHWARZER", label = "Schwartzer", model = "schwarzer" },
            { audio = "SENTINEL3", label = "Sentinel Classic", model = "sentinel3" },
            { audio = "SEVEN70", label = "Seven-70", model = "seven70" },
            { audio = "SPECTER", label = "Specter", model = "specter" },
            { audio = "SPECTER2", label = "Specter Custom", model = "specter2" },
            { audio = "STREITER", label = "Streiter", model = "streiter" },
            { audio = "SUGOI", label = "Sugoi", model = "sugoi" },
            { audio = "SULTAN", label = "Sultan", model = "sultan" },
            { audio = "SULTAN2", label = "Sultan Classic", model = "sultan2" },
            { audio = "SURANO", label = "Surano", model = "surano" },
            { audio = "TAMPA2", label = "Drift Tampa", model = "tampa2" },
            { audio = "TROPOS", label = "Tropos Rallye", model = "tropos" },
            { audio = "VERLIERER2", label = "Verlierer", model = "verlierer2" },
            { audio = "ZR350", label = "ZR350", model = "zr350" },
        }
    },
    {
        name = "Muscle",
        icon = "car",
        vehicles = {
            { audio = "BLADE", label = "Blade", model = "blade" },
            { audio = "BUCCANEER", label = "Buccaneer", model = "buccaneer" },
            { audio = "BUCCANEER2", label = "Buccaneer Custom", model = "buccaneer2" },
            { audio = "CHINO", label = "Chino", model = "chino" },
            { audio = "CHINO2", label = "Chino Custom", model = "chino2" },
            { audio = "CLIQUE", label = "Clique", model = "clique" },
            { audio = "COQUETTE3", label = "Coquette BlackFin", model = "coquette3" },
            { audio = "DEVIANT", label = "Deviant", model = "deviant" },
            { audio = "DOMINATOR", label = "Dominator", model = "dominator" },
            { audio = "DOMINATOR2", label = "Pisswasser Dominator", model = "dominator2" },
            { audio = "DOMINATOR3", label = "Dominator GTX", model = "dominator3" },
            { audio = "DUKES", label = "Dukes", model = "dukes" },
            { audio = "DUKES2", label = "Duke O'Death", model = "dukes2" },
            { audio = "ELLIE", label = "Ellie", model = "ellie" },
            { audio = "FACTION", label = "Faction", model = "faction" },
            { audio = "FACTION2", label = "Faction Custom", model = "faction2" },
            { audio = "FACTION3", label = "Faction Donk", model = "faction3" },
            { audio = "GAUNTLET", label = "Gauntlet", model = "gauntlet" },
            { audio = "GAUNTLET2", label = "Redwood Gauntlet", model = "gauntlet2" },
            { audio = "GAUNTLET3", label = "Gauntlet Classic", model = "gauntlet3" },
            { audio = "GAUNTLET4", label = "Gauntlet Hellfire", model = "gauntlet4" },
            { audio = "HERMES", label = "Hermes", model = "hermes" },
            { audio = "HOTKNIFE", label = "Hotknife", model = "hotknife" },
            { audio = "HUSTLER", label = "Hustler", model = "hustler" },
            { audio = "IMPALER", label = "Impaler", model = "impaler" },
            { audio = "IMPERATOR", label = "Imperator", model = "imperator" },
            { audio = "LURCHER", label = "Lurcher", model = "lurcher" },
            { audio = "MOONBEAM", label = "Moonbeam", model = "moonbeam" },
            { audio = "MOONBEAM2", label = "Moonbeam Custom", model = "moonbeam2" },
            { audio = "NIGHTSHADE", label = "Nightshade", model = "nightshade" },
            { audio = "PEYOTE2", label = "Peyote Gasser", model = "peyote2" },
            { audio = "PHOENIX", label = "Phoenix", model = "phoenix" },
            { audio = "PICADOR", label = "Picador", model = "picador" },
            { audio = "RATLOADER", label = "Rat-Loader", model = "ratloader" },
            { audio = "RATLOADER2", label = "Rat-Truck", model = "ratloader2" },
            { audio = "RUINER", label = "Ruiner", model = "ruiner" },
            { audio = "RUINER2", label = "Ruiner 2000", model = "ruiner2" },
            { audio = "SABREGT", label = "Sabre Turbo", model = "sabregt" },
            { audio = "SABREGT2", label = "Sabre Turbo Custom", model = "sabregt2" },
            { audio = "SLAMVAN", label = "Slamvan", model = "slamvan" },
            { audio = "SLAMVAN2", label = "Lost Slamvan", model = "slamvan2" },
            { audio = "SLAMVAN3", label = "Slamvan Custom", model = "slamvan3" },
            { audio = "STALION", label = "Stallion", model = "stalion" },
            { audio = "STALION2", label = "Burger Shot Stallion", model = "stalion2" },
            { audio = "TAMPA", label = "Tampa", model = "tampa" },
            { audio = "TULIP", label = "Tulip", model = "tulip" },
            { audio = "VAMOS", label = "Vamos", model = "vamos" },
            { audio = "VIGERO", label = "Vigero", model = "vigero" },
            { audio = "VIRGO", label = "Virgo", model = "virgo" },
            { audio = "VIRGO2", label = "Virgo Classic Custom", model = "virgo2" },
            { audio = "VIRGO3", label = "Virgo Classic", model = "virgo3" },
            { audio = "VOODOO", label = "Voodoo", model = "voodoo" },
            { audio = "VOODOO2", label = "Voodoo Custom", model = "voodoo2" },
            { audio = "YOSEMITE", label = "Yosemite", model = "yosemite" },
        }
    },
    {
        name = "Motorcycles",
        icon = "motorcycle",
        vehicles = {
            { audio = "AKUMA", label = "Akuma", model = "akuma" },
            { audio = "AVARUS", label = "Avarus", model = "avarus" },
            { audio = "BAGGER", label = "Bagger", model = "bagger" },
            { audio = "BATI", label = "Bati 801", model = "bati" },
            { audio = "BATI2", label = "Bati 801RR", model = "bati2" },
            { audio = "BF400", label = "BF400", model = "bf400" },
            { audio = "CARBONRS", label = "Carbon RS", model = "carbonrs" },
            { audio = "CHIMERA", label = "Chimera", model = "chimera" },
            { audio = "CLIFFHANGER", label = "Cliffhanger", model = "cliffhanger" },
            { audio = "DAEMON", label = "Daemon", model = "daemon" },
            { audio = "DAEMON2", label = "Daemon Custom", model = "daemon2" },
            { audio = "DEFILER", label = "Defiler", model = "defiler" },
            { audio = "DEATHBIKE", label = "Deathbike", model = "deathbike" },
            { audio = "DIABLOUS", label = "Diabolus", model = "diablous" },
            { audio = "DIABLOUS2", label = "Diabolus Custom", model = "diablous2" },
            { audio = "DOUBLE", label = "Double T", model = "double" },
            { audio = "ENDURO", label = "Enduro", model = "enduro" },
            { audio = "ESSKEY", label = "Esskey", model = "esskey" },
            { audio = "FAGGIO", label = "Faggio", model = "faggio" },
            { audio = "FAGGIO2", label = "Faggio Sport", model = "faggio2" },
            { audio = "FAGGIO3", label = "Faggio Mod", model = "faggio3" },
            { audio = "FCR", label = "FCR 1000", model = "fcr" },
            { audio = "FCR2", label = "FCR 1000 Custom", model = "fcr2" },
            { audio = "GARGOYLE", label = "Gargoyle", model = "gargoyle" },
            { audio = "HAKUCHOU", label = "Hakuchou", model = "hakuchou" },
            { audio = "HAKUCHOU2", label = "Hakuchou Drag", model = "hakuchou2" },
            { audio = "HEXER", label = "Hexer", model = "hexer" },
            { audio = "INNOVATION", label = "Innovation", model = "innovation" },
            { audio = "LECTRO", label = "Lectro", model = "lectro" },
            { audio = "MANCHEZ", label = "Manchez", model = "manchez" },
            { audio = "NEMESIS", label = "Nemesis", model = "nemesis" },
            { audio = "NIGHTBLADE", label = "Nightblade", model = "nightblade" },
            { audio = "OPPRESSOR", label = "Oppressor", model = "oppressor" },
            { audio = "OPPRESSOR2", label = "Oppressor Mk II", model = "oppressor2" },
            { audio = "PCJ", label = "PCJ 600", model = "pcj" },
            { audio = "RATBIKE", label = "Rat Bike", model = "ratbike" },
            { audio = "RUFFIAN", label = "Ruffian", model = "ruffian" },
            { audio = "SANCHEZ", label = "Sanchez", model = "sanchez" },
            { audio = "SANCHEZ2", label = "Sanchez (Livery)", model = "sanchez2" },
            { audio = "SANCTUS", label = "Sanctus", model = "sanctus" },
            { audio = "SHOTARO", label = "Shotaro", model = "shotaro" },
            { audio = "SOVEREIGN", label = "Sovereign", model = "sovereign" },
            { audio = "STRYDER", label = "Stryder", model = "stryder" },
            { audio = "THRUST", label = "Thrust", model = "thrust" },
            { audio = "VADER", label = "Vader", model = "vader" },
            { audio = "VINDICATOR", label = "Vindicator", model = "vindicator" },
            { audio = "VORTEX", label = "Vortex", model = "vortex" },
            { audio = "WOLFSBANE", label = "Wolfsbane", model = "wolfsbane" },
            { audio = "ZOMBIEA", label = "Zombie Bobber", model = "zombiea" },
            { audio = "ZOMBIEB", label = "Zombie Chopper", model = "zombieb" },
        }
    },
    {
        name = "Emergency",
        icon = "siren",
        vehicles = {
            { audio = "AMBULANCE", label = "Ambulance", model = "ambulance" },
            { audio = "FBI", label = "FIB", model = "fbi" },
            { audio = "FBI2", label = "FIB SUV", model = "fbi2" },
            { audio = "FIRETRUK", label = "Fire Truck", model = "firetruk" },
            { audio = "LGUARD", label = "Lifeguard", model = "lguard" },
            { audio = "PBUS", label = "Police Prison Bus", model = "pbus" },
            { audio = "POLICE", label = "Police Cruiser", model = "police" },
            { audio = "POLICE2", label = "Police Cruiser 2", model = "police2" },
            { audio = "POLICE3", label = "Police Cruiser 3", model = "police3" },
            { audio = "POLICE4", label = "Police Cruiser 4", model = "police4" },
            { audio = "POLICEB", label = "Police Bike", model = "policeb" },
            { audio = "POLICEOLD1", label = "Police Rancher", model = "policeold1" },
            { audio = "POLICEOLD2", label = "Police Roadcruiser", model = "policeold2" },
            { audio = "POLICET", label = "Police Transporter", model = "policet" },
            { audio = "POLMAV", label = "Police Maverick", model = "polmav" },
            { audio = "PRANGER", label = "Park Ranger", model = "pranger" },
            { audio = "PREDATOR", label = "Predator", model = "predator" },
            { audio = "RIOT", label = "RCV", model = "riot" },
            { audio = "RIOT2", label = "RCV 2", model = "riot2" },
            { audio = "SHERIFF", label = "Sheriff Cruiser", model = "sheriff" },
            { audio = "SHERIFF2", label = "Sheriff SUV", model = "sheriff2" },
        }
    },
    {
        name = "Military",
        icon = "tank",
        vehicles = {
            { audio = "APC", label = "APC", model = "apc" },
            { audio = "BARRACKS", label = "Barracks", model = "barracks" },
            { audio = "BARRACKS2", label = "Barracks Semi", model = "barracks2" },
            { audio = "BARRACKS3", label = "Barracks (Canvas)", model = "barracks3" },
            { audio = "BARRAGE", label = "Barrage", model = "barrage" },
            { audio = "CHERNOBOG", label = "Chernobog", model = "chernobog" },
            { audio = "CRUSADER", label = "Crusader", model = "crusader" },
            { audio = "HALFTRACK", label = "Half-track", model = "halftrack" },
            { audio = "KHANJALI", label = "TM-02 Khanjali", model = "khanjali" },
            { audio = "RHINO", label = "Rhino Tank", model = "rhino" },
            { audio = "SCARAB", label = "Scarab", model = "scarab" },
            { audio = "THRUSTER", label = "Thruster", model = "thruster" },
            { audio = "TRAILERSMALL2", label = "Anti-Aircraft Trailer", model = "trailersmall2" },
        }
    },
    {
        name = "Helicopters",
        icon = "helicopter",
        vehicles = {
            { audio = "AKULA", label = "Akula", model = "akula" },
            { audio = "ANNIHILATOR", label = "Annihilator", model = "annihilator" },
            { audio = "BUZZARD", label = "Buzzard", model = "buzzard" },
            { audio = "BUZZARD2", label = "Buzzard (Unarmed)", model = "buzzard2" },
            { audio = "CARGOBOB", label = "Cargobob", model = "cargobob" },
            { audio = "CARGOBOB2", label = "Cargobob 2", model = "cargobob2" },
            { audio = "CARGOBOB3", label = "Cargobob 3", model = "cargobob3" },
            { audio = "CARGOBOB4", label = "Cargobob 4", model = "cargobob4" },
            { audio = "FROGGER", label = "Frogger", model = "frogger" },
            { audio = "FROGGER2", label = "Frogger (FIB)", model = "frogger2" },
            { audio = "HAVOK", label = "Havok", model = "havok" },
            { audio = "HUNTER", label = "Hunter", model = "hunter" },
            { audio = "MAVERICK", label = "Maverick", model = "maverick" },
            { audio = "SAVAGE", label = "Savage", model = "savage" },
            { audio = "SEASPARROW", label = "Sea Sparrow", model = "seasparrow" },
            { audio = "SKYLIFT", label = "Skylift", model = "skylift" },
            { audio = "SUPERVOLITO", label = "SuperVolito", model = "supervolito" },
            { audio = "SUPERVOLITO2", label = "SuperVolito Carbon", model = "supervolito2" },
            { audio = "SWIFT", label = "Swift", model = "swift" },
            { audio = "SWIFT2", label = "Swift Deluxe", model = "swift2" },
            { audio = "VALKYRIE", label = "Valkyrie", model = "valkyrie" },
            { audio = "VALKYRIE2", label = "Valkyrie MOD.0", model = "valkyrie2" },
            { audio = "VOLATUS", label = "Volatus", model = "volatus" },
        }
    },
    {
        name = "Planes",
        icon = "plane",
        vehicles = {
            { audio = "ALPHAZ1", label = "Alpha-Z1", model = "alphaz1" },
            { audio = "AVENGER", label = "Avenger", model = "avenger" },
            { audio = "AVENGER2", label = "Avenger 2", model = "avenger2" },
            { audio = "BESRA", label = "Besra", model = "besra" },
            { audio = "BLIMP", label = "Blimp", model = "blimp" },
            { audio = "BLIMP2", label = "Blimp 2", model = "blimp2" },
            { audio = "BLIMP3", label = "Blimp 3", model = "blimp3" },
            { audio = "BOMBUSHKA", label = "Bombushka", model = "bombushka" },
            { audio = "CARGOPLANE", label = "Cargo Plane", model = "cargoplane" },
            { audio = "CUBAN800", label = "Cuban 800", model = "cuban800" },
            { audio = "DODO", label = "Dodo", model = "dodo" },
            { audio = "DUSTER", label = "Duster", model = "duster" },
            { audio = "HOWARD", label = "Howard NX-25", model = "howard" },
            { audio = "HYDRA", label = "Hydra", model = "hydra" },
            { audio = "JET", label = "Private Jet", model = "jet" },
            { audio = "LAZER", label = "P-996 LAZER", model = "lazer" },
            { audio = "LUXOR", label = "Luxor", model = "luxor" },
            { audio = "LUXOR2", label = "Luxor Deluxe", model = "luxor2" },
            { audio = "MAMMATUS", label = "Mammatus", model = "mammatus" },
            { audio = "MICROLIGHT", label = "Ultralight", model = "microlight" },
            { audio = "MILJET", label = "Miljet", model = "miljet" },
            { audio = "MOGUL", label = "Mogul", model = "mogul" },
            { audio = "MOLOTOK", label = "V-65 Molotok", model = "molotok" },
            { audio = "NIMBUS", label = "Nimbus", model = "nimbus" },
            { audio = "NOKOTA", label = "P-45 Nokota", model = "nokota" },
            { audio = "PYRO", label = "Pyro", model = "pyro" },
            { audio = "ROGUE", label = "Rogue", model = "rogue" },
            { audio = "SEABREEZE", label = "Seabreeze", model = "seabreeze" },
            { audio = "SHAMAL", label = "Shamal", model = "shamal" },
            { audio = "STARLING", label = "LF-22 Starling", model = "starling" },
            { audio = "STRIKEFORCE", label = "B-11 Strikeforce", model = "strikeforce" },
            { audio = "STUNT", label = "Mallard", model = "stunt" },
            { audio = "TITAN", label = "Titan", model = "titan" },
            { audio = "TULA", label = "Tula", model = "tula" },
            { audio = "VELUM", label = "Velum", model = "velum" },
            { audio = "VELUM2", label = "Velum 5-Seater", model = "velum2" },
            { audio = "VESTRA", label = "Vestra", model = "vestra" },
            { audio = "VOLATOL", label = "Volatol", model = "volatol" },
        }
    },
    {
        name = "Boats",
        icon = "boat",
        vehicles = {
            { audio = "DINGHY", label = "Dinghy", model = "dinghy" },
            { audio = "DINGHY2", label = "Dinghy 2", model = "dinghy2" },
            { audio = "DINGHY3", label = "Dinghy 3", model = "dinghy3" },
            { audio = "DINGHY4", label = "Dinghy 4", model = "dinghy4" },
            { audio = "JETMAX", label = "Jetmax", model = "jetmax" },
            { audio = "MARQUIS", label = "Marquis", model = "marquis" },
            { audio = "SEASHARK", label = "Seashark", model = "seashark" },
            { audio = "SEASHARK2", label = "Seashark 2", model = "seashark2" },
            { audio = "SEASHARK3", label = "Seashark 3", model = "seashark3" },
            { audio = "SPEEDER", label = "Speeder", model = "speeder" },
            { audio = "SPEEDER2", label = "Speeder 2", model = "speeder2" },
            { audio = "SQUALO", label = "Squalo", model = "squalo" },
            { audio = "SUBMERSIBLE", label = "Kraken", model = "submersible" },
            { audio = "SUBMERSIBLE2", label = "Kraken 2", model = "submersible2" },
            { audio = "SUNTRAP", label = "Suntrap", model = "suntrap" },
            { audio = "TORO", label = "Toro", model = "toro" },
            { audio = "TORO2", label = "Toro 2", model = "toro2" },
            { audio = "TROPIC", label = "Tropic", model = "tropic" },
            { audio = "TROPIC2", label = "Tropic 2", model = "tropic2" },
            { audio = "TUG", label = "Tug", model = "tug" },
        }
    },
    {
        name = "SUVs",
        icon = "truck",
        vehicles = {
            { audio = "BALLER", label = "Baller", model = "baller" },
            { audio = "BALLER2", label = "Baller LE", model = "baller2" },
            { audio = "BALLER3", label = "Baller LE LWB", model = "baller3" },
            { audio = "BALLER4", label = "Baller LE Armored", model = "baller4" },
            { audio = "BALLER5", label = "Baller LE LWB Armored", model = "baller5" },
            { audio = "BALLER6", label = "Baller ST", model = "baller6" },
            { audio = "BJXL", label = "BeeJay XL", model = "bjxl" },
            { audio = "CAVALCADE", label = "Cavalcade", model = "cavalcade" },
            { audio = "CAVALCADE2", label = "Cavalcade 2", model = "cavalcade2" },
            { audio = "CONTENDER", label = "Contender", model = "contender" },
            { audio = "DUBSTA", label = "Dubsta", model = "dubsta" },
            { audio = "DUBSTA2", label = "Dubsta 2", model = "dubsta2" },
            { audio = "DUBSTA3", label = "Dubsta 6x6", model = "dubsta3" },
            { audio = "FQ2", label = "FQ 2", model = "fq2" },
            { audio = "GRANGER", label = "Granger", model = "granger" },
            { audio = "GRESLEY", label = "Gresley", model = "gresley" },
            { audio = "HABANERO", label = "Habanero", model = "habanero" },
            { audio = "HUNTLEY", label = "Huntley S", model = "huntley" },
            { audio = "LANDSTALKER", label = "Landstalker", model = "landstalker" },
            { audio = "LANDSTALKER2", label = "Landstalker XL", model = "landstalker2" },
            { audio = "MESA", label = "Mesa", model = "mesa" },
            { audio = "MESA2", label = "Mesa (Merryweather)", model = "mesa2" },
            { audio = "MESA3", label = "Mesa 3", model = "mesa3" },
            { audio = "NOVAK", label = "Novak", model = "novak" },
            { audio = "PATRIOT", label = "Patriot", model = "patriot" },
            { audio = "PATRIOT2", label = "Patriot Stretch", model = "patriot2" },
            { audio = "RADI", label = "Radius", model = "radi" },
            { audio = "REBLA", label = "Rebla GTS", model = "rebla" },
            { audio = "ROCOTO", label = "Rocoto", model = "rocoto" },
            { audio = "SEMINOLE", label = "Seminole", model = "seminole" },
            { audio = "SEMINOLE2", label = "Seminole Frontier", model = "seminole2" },
            { audio = "SERRANO", label = "Serrano", model = "serrano" },
            { audio = "SQUADDIE", label = "Squaddie", model = "squaddie" },
            { audio = "TOROS", label = "Toros", model = "toros" },
            { audio = "XLS", label = "XLS", model = "xls" },
            { audio = "XLS2", label = "XLS (Armored)", model = "xls2" },
        }
    },
    {
        name = "Trucks",
        icon = "truck",
        vehicles = {
            { audio = "BENSON", label = "Benson", model = "benson" },
            { audio = "BIFF", label = "Biff", model = "biff" },
            { audio = "HAULER", label = "Hauler", model = "hauler" },
            { audio = "HAULER2", label = "Hauler Custom", model = "hauler2" },
            { audio = "MULE", label = "Mule", model = "mule" },
            { audio = "MULE2", label = "Mule 2", model = "mule2" },
            { audio = "MULE3", label = "Mule 3", model = "mule3" },
            { audio = "MULE4", label = "Mule 4", model = "mule4" },
            { audio = "PACKER", label = "Packer", model = "packer" },
            { audio = "PHANTOM", label = "Phantom", model = "phantom" },
            { audio = "PHANTOM2", label = "Phantom Wedge", model = "phantom2" },
            { audio = "PHANTOM3", label = "Phantom Custom", model = "phantom3" },
            { audio = "POUNDER", label = "Pounder", model = "pounder" },
            { audio = "POUNDER2", label = "Pounder Custom", model = "pounder2" },
            { audio = "STOCKADE", label = "Stockade", model = "stockade" },
            { audio = "STOCKADE3", label = "Stockade 3", model = "stockade3" },
            { audio = "BISON", label = "Bison", model = "bison" },
            { audio = "BISON2", label = "Bison 2", model = "bison2" },
            { audio = "BISON3", label = "Bison 3", model = "bison3" },
            { audio = "BOBCATXL", label = "Bobcat XL", model = "bobcatxl" },
            { audio = "BODHI2", label = "Bodhi", model = "bodhi2" },
            { audio = "DUBSTA3", label = "Dubsta 6x6", model = "dubsta3" },
            { audio = "GUARDIAN", label = "Guardian", model = "guardian" },
            { audio = "INSURGENT", label = "Insurgent", model = "insurgent" },
            { audio = "INSURGENT2", label = "Insurgent Pickup", model = "insurgent2" },
            { audio = "INSURGENT3", label = "Insurgent Pickup Custom", model = "insurgent3" },
            { audio = "KAMACHO", label = "Kamacho", model = "kamacho" },
            { audio = "MARSHALL", label = "Marshall", model = "marshall" },
            { audio = "MONSTER", label = "Liberator", model = "monster" },
            { audio = "NIGHTSHARK", label = "Nightshark", model = "nightshark" },
            { audio = "RIATA", label = "Riata", model = "riata" },
            { audio = "SANDKING", label = "Sandking XL", model = "sandking" },
            { audio = "SANDKING2", label = "Sandking SWB", model = "sandking2" },
            { audio = "TECHNICAL", label = "Technical", model = "technical" },
            { audio = "TECHNICAL2", label = "Technical Aqua", model = "technical2" },
            { audio = "TECHNICAL3", label = "Technical Custom", model = "technical3" },
        }
    },
    {
        name = "Sedans",
        icon = "car",
        vehicles = {
            { audio = "ASEA", label = "Asea", model = "asea" },
            { audio = "ASEA2", label = "Asea (Snow)", model = "asea2" },
            { audio = "ASTEROPE", label = "Asterope", model = "asterope" },
            { audio = "COG55", label = "Cognoscenti 55", model = "cog55" },
            { audio = "COG552", label = "Cognoscenti 55 Armored", model = "cog552" },
            { audio = "COGNOSCENTI", label = "Cognoscenti", model = "cognoscenti" },
            { audio = "COGNOSCENTI2", label = "Cognoscenti Armored", model = "cognoscenti2" },
            { audio = "EMPEROR", label = "Emperor", model = "emperor" },
            { audio = "EMPEROR2", label = "Emperor 2", model = "emperor2" },
            { audio = "EMPEROR3", label = "Emperor 3", model = "emperor3" },
            { audio = "FUGITIVE", label = "Fugitive", model = "fugitive" },
            { audio = "GLENDALE", label = "Glendale", model = "glendale" },
            { audio = "GLENDALE2", label = "Glendale Custom", model = "glendale2" },
            { audio = "INGOT", label = "Ingot", model = "ingot" },
            { audio = "INTRUDER", label = "Intruder", model = "intruder" },
            { audio = "PREMIER", label = "Premier", model = "premier" },
            { audio = "PRIMO", label = "Primo", model = "primo" },
            { audio = "PRIMO2", label = "Primo Custom", model = "primo2" },
            { audio = "REGINA", label = "Regina", model = "regina" },
            { audio = "ROMERO", label = "Romero Hearse", model = "romero" },
            { audio = "SCHAFTER2", label = "Schafter", model = "schafter2" },
            { audio = "STAFFORD", label = "Stafford", model = "stafford" },
            { audio = "STANIER", label = "Stanier", model = "stanier" },
            { audio = "STRATUM", label = "Stratum", model = "stratum" },
            { audio = "STRETCH", label = "Stretch", model = "stretch" },
            { audio = "SUPERD", label = "Super Diamond", model = "superd" },
            { audio = "SURGE", label = "Surge", model = "surge" },
            { audio = "TAILGATER", label = "Tailgater", model = "tailgater" },
            { audio = "WARRENER", label = "Warrener", model = "warrener" },
            { audio = "WASHINGTON", label = "Washington", model = "washington" },
        }
    },
    {
        name = "Classic",
        icon = "car",
        vehicles = {
            { audio = "ARDENT", label = "Ardent", model = "ardent" },
            { audio = "BTYPE", label = "Roosevelt", model = "btype" },
            { audio = "BTYPE2", label = "Roosevelt Valor", model = "btype2" },
            { audio = "BTYPE3", label = "Franken Stange", model = "btype3" },
            { audio = "CASCO", label = "Casco", model = "casco" },
            { audio = "CHEETAH2", label = "Cheetah Classic", model = "cheetah2" },
            { audio = "COQUETTE2", label = "Coquette Classic", model = "coquette2" },
            { audio = "DELUXO", label = "Deluxo", model = "deluxo" },
            { audio = "DYNASTY", label = "Dynasty", model = "dynasty" },
            { audio = "FAGALOA", label = "Fagaloa", model = "fagaloa" },
            { audio = "FELTZER3", label = "Stirling GT", model = "feltzer3" },
            { audio = "GT500", label = "GT500", model = "gt500" },
            { audio = "INFERNUS2", label = "Infernus Classic", model = "infernus2" },
            { audio = "JB700", label = "JB 700", model = "jb700" },
            { audio = "JB7002", label = "JB 700W", model = "jb7002" },
            { audio = "MAMBA", label = "Mamba", model = "mamba" },
            { audio = "MANANA", label = "Manana", model = "manana" },
            { audio = "MANANA2", label = "Manana Custom", model = "manana2" },
            { audio = "MICHELLI", label = "Michelli GT", model = "michelli" },
            { audio = "MONROE", label = "Monroe", model = "monroe" },
            { audio = "NEBULA", label = "Nebula Turbo", model = "nebula" },
            { audio = "PEYOTE", label = "Peyote", model = "peyote" },
            { audio = "PEYOTE3", label = "Peyote Custom", model = "peyote3" },
            { audio = "PIGALLE", label = "Pigalle", model = "pigalle" },
            { audio = "RAPIDGT3", label = "Rapid GT Classic", model = "rapidgt3" },
            { audio = "RETINUE", label = "Retinue", model = "retinue" },
            { audio = "RETINUE2", label = "Retinue Mk II", model = "retinue2" },
            { audio = "SAVESTRA", label = "Savestra", model = "savestra" },
            { audio = "STINGER", label = "Stinger", model = "stinger" },
            { audio = "STINGERGT", label = "Stinger GT", model = "stingergt" },
            { audio = "STROMBERG", label = "Stromberg", model = "stromberg" },
            { audio = "SWINGER", label = "Swinger", model = "swinger" },
            { audio = "TORERO", label = "Torero", model = "torero" },
            { audio = "TORNADO", label = "Tornado", model = "tornado" },
            { audio = "TORNADO2", label = "Tornado Cabrio", model = "tornado2" },
            { audio = "TORNADO3", label = "Tornado (Rusty)", model = "tornado3" },
            { audio = "TORNADO4", label = "Tornado 4", model = "tornado4" },
            { audio = "TORNADO5", label = "Tornado Custom", model = "tornado5" },
            { audio = "TORNADO6", label = "Tornado Rat Rod", model = "tornado6" },
            { audio = "TURISMO2", label = "Turismo Classic", model = "turismo2" },
            { audio = "VISERIS", label = "Viseris", model = "viseris" },
            { audio = "Z190", label = "190z", model = "z190" },
            { audio = "ZTYPE", label = "Z-Type", model = "ztype" },
        }
    },
}

print(string.format("[es_soundtester] Loaded %d vehicle audio categories", #VehicleAudio.Categories))
